site_name:        Flax.jl
<<<<<<< HEAD
repo_url:         https://github.com/essenciary/Genie.jl
site_description: Genie is a full-stack MVC web framework that promotes a streamlined and efficient workflow for developing modern web applications.
=======
repo_url:         https://github.com/essenciary/Flax.jl
site_description: Flax is the view layer and the templating library of Genie.jl, the high-performance high-productivity Julia web framework.
>>>>>>> v0.1
site_author:      essenciary

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
